### ISSUE TITLE
BuildTools not compatible with latest PlotSquared release

### ISSUE THREAD

**Issue by addstar** [AddstarMC/BuildTools#1]
We've been using the "[legacy](https://ci.athion.net/job/PlotSquared-Legacy/)" builds for a long time, now after finally using the [latest PlotSquared](https://ci.athion.net/job/PlotSquared-Releases/) release (actually using v4.221 from SpigotMC.. now BT is not compatible with the PlotAPI:

```
00:15:46 [INFO]: Enabling BuildTools v1.1-SNAPSHOT-24
00:15:46 [ERROR]: Error occurred while enabling BuildTools v1.1-SNAPSHOT-24 (Is it up to date?)
java.lang.NoClassDefFoundError: com/intellectualcrafters/plot/api/PlotAPI
        at au.com.mineauz.buildtools.protection.PSPlugin.<init>(PSPlugin.java:14) ~[?:?]
        at au.com.mineauz.buildtools.BTPlugin.onEnable(BTPlugin.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:334) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:608) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:570) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:431) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:316) ~[patched_1.13.2.jar:git-Paper-624]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.intellectualcrafters.plot.api.PlotAPI
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[patched_1.13.2.jar:git-Paper-624]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[patched_1.13.2.jar:git-Paper-624]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
        ... 13 more
```

**Comment by addstar** [comment]
Example of maven repo and dependency usage:
https://github.com/IntellectualSites/plot2dynmap/blob/master/pom.xml#L11
